openapi: 3.0.0
info:
  title: eMeetting API
  # description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  # version: 0.1.9

servers:
  - url: http://localhost:3301
    # description: Optional server description, e.g. Main (production) server
  - url: http://example.com
    # description: Optional server description, e.g. Internal staging server for testing

paths:
  /api/v1/provinces:
    get:
      summary: Provinces
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /api/v1/amphures/{province_id}:
    get:
      summary: Amphures
      parameters:
        - name: province_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK

  /api/v1/tombons/{amphure_id}:
    get:
      summary: Tombons
      parameters:
        - name: amphure_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK

  /api/v1/zipcode/{id}:
    get:
      summary: Zipcode
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK     



  /api/v1/menuitems:
    get:
      summary: menuitems
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                  
    post:
        summary: Create a new book
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/title'
     responses:
       200:
         description: The created book.
       content:
          application/json:
             schema:
                $ref: '#/components/schemas/title'